### ISSUE TITLE
Time axis ticks trouble

### ISSUE THREAD

**Issue by RalfNorthman** [terezka/charts#11]
This package looks really promising!

Version used: 13.0.1

I noticed something strange on my axis with ticks and labels using `CA.times`:

![time-axis-59s](https://user-images.githubusercontent.com/26719710/124881723-f8c7cc80-dfcf-11eb-9892-032d8a09d64e.png)

For other similar intervals it looks as expected:

![reasonable-axis](https://user-images.githubusercontent.com/26719710/124882072-50663800-dfd0-11eb-9d84-2adcc2f4b97e.png)

Another interval gave some good clues about what is going on:

![time-axis-rounding](https://user-images.githubusercontent.com/26719710/124882435-a9ce6700-dfd0-11eb-9ebd-3160ceda1f4d.png)

The 07:14 label above seems to belong to a 07:14:14 value. It looks like some rounding down to the new, higher "time unit" (minute in this case) for the first value larger than the "time unit" is the culprit.

Without having looked at the source code:
A solution would be to not round the first value of any given minute or better yet: always find the nice tick positions, i.e. whole, exact time units for the "larger" unit and multiples of 5 for the "smaller" unit (for minutes and seconds).

**Comment by terezka** [comment]
Yeah, I've seen it do that too once! Your theory sounds right- I will look into it! Thanks for taking the time to write the feedback!

**Comment by terezka** [comment]
I think this may be fixed with https://github.com/terezka/charts/commit/d60ca028b6ea2400cd83f0da0742518e0b9bade2!

**Comment by RalfNorthman** [comment]
Excellent news!

And I just noticed elm-charts is updated as well. Great!
