### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by David-Klemenc** [terezka/charts#15]
In the elm.json file I would expect the `"elm-explorations/test": "1.2.2 <= v < 2.0.0",`to be in the test-dependencies?

```json
{
    "type": "package",
    "name": "terezka/charts",
    "summary": "SVG charts components in Elm.",
    "license": "BSD-3-Clause",
    "version": "17.0.0",
    "exposed-modules": [
        "Chart.Attributes",
        "Chart.Events",
        "Chart.Item",
        "Chart.Svg",
        "Chart"
    ],
    "elm-version": "0.19.0 <= v < 0.20.0",
    "dependencies": {
        "debois/elm-dom": "1.3.0 <= v < 2.0.0",
        "elm/core": "1.0.0 <= v < 2.0.0",
        "elm/html": "1.0.0 <= v < 2.0.0",
        "elm/json": "1.0.0 <= v < 2.0.0",
        "elm/regex": "1.0.0 <= v < 2.0.0",
        "elm/svg": "1.0.1 <= v < 2.0.0",
        "elm/time": "1.0.0 <= v < 2.0.0",
        "myrho/elm-round": "1.0.4 <= v < 2.0.0",
        "ryannhg/date-format": "2.3.0 <= v < 3.0.0",
        "terezka/intervals": "2.0.0 <= v < 3.0.0"
    },
    "test-dependencies": {
        "elm-explorations/test": "1.2.2 <= v < 2.0.0", // this line
    }
}
```

I tried reading the docs on elm.json but they seem to be outdated a bit ... I think that you do not want to ship the tests in a library?

[elm.json](https://github.com/elm/compiler/blob/master/docs/elm.json/application.md)

Also [debois/elm-dom](https://github.com/debois/elm-dom) is no longer maintained actively.

You are using `DOM` in `charts/src/Internal/Svg.elm` and it is also imported in `charts/src/Chart/Svg.elm` but not used

You could get the boundingClientRect with `Browser.Dom.getElement` - getting the parent element would be a bit more tricky.

**Comment by terezka** [comment]
Thanks for catching that! I'll remove the test dep.

I don't think it's a problem that `debois/elm-dom` isn't maintained anymore- if there is anything wrong, I'll just fork the lib and fix it myself. It's a very simple library after all! I'd rather not need the user to start hooking up tasks to do a tooltip!

**Comment by David-Klemenc** [comment]
Yes I was also thinking that `elm-dom` could just be copied (at some point in the future). Anyway thank you for the nice library!
